# Generated by Django 3.1.14 on 2022-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_auto_20220904_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
