# Generated by Django 3.1.14 on 2022-09-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20220919_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evolution_p',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='previous_evolution_p',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='pokemon_entities.pokemon', verbose_name='В кого эволюционирует'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционирует'),
        ),
    ]
