# Generated by Django 3.1.14 on 2022-09-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20220913_2215'),
        ('pokemon_entities', '0001_auto_20220916_1115'),
    ]

    operations = [
    ]
