# Generated by Django 3.1.14 on 2022-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_merge_20220916_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(default='Описание', max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(default=models.CharField(max_length=20, verbose_name='Имя на русском'), max_length=20, verbose_name='Имя на английском'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(default=models.CharField(max_length=20, verbose_name='Имя на русском'), max_length=20, verbose_name='Имя на японском'),
        ),
    ]
