# Generated by Django 3.1.14 on 2022-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20221014_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default=' ', max_length=35, verbose_name='Имя на английском'),
        ),
    ]
